name : RAG CI
on:
  pull_request:
    paths-ignore:
      - "docs/**"
      - "*.md"
      - ".gitignore"
      - "CODEOWNERS"
      - "LICENSE"
  push:
    branches:
      - master
      - main

jobs:
  build:
    runs-on : ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses : actions/setup-go@v5
        with:
          go-version: ">=1.22.0"
      - name : Build
        run: cd rag-gateway && make build
      - name : Test
        run : cd rag-gateway && go test -race ./...
  build-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3 
      - name: Build image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./package/gateway/Dockerfile
          push: false
          tags: ghcr.io/synaptic/rag-gateway:dev
          platforms: linux/amd64
